### PR TITLE
use packages-eu mirror to reduce install time

### PR DESCRIPTION
**Pull request by basisbit**
use packages-eu mirror to reduce install time

### CODE REVIEW

**Comment by genofire** [comment]
We switch already several times between the repo servers.

...

Do you like to but the URL into a variables und a default value under `defaults/main.yml`?

**Comment by n0emis** [comment]
> Do you like to but the URL into a variables und a default value under `defaults/main.yml`?

I would support this, then it is easier to change for users of the role.

**Comment by basisbit** [comment]
@genofire I looked at the git history and didn't see the package source being changed at all. Which commit are you referring to?

**Comment by n0emis** [comment]
It was this PR: https://github.com/n0emis/ansible-role-bigbluebutton/pull/7

**Comment by basisbit** [comment]
But that is not the parr which this PR was changing.
Anyways, I don't know how to ansible, and don't have the free time to learn it.
I assume this will not be merged like this and someone else will just do a PR again without attribution.

**Pull request closed without merging**
